SG-34320 - Rebranding
shotgunsoftware/tk-multi-breakdown2 pull request #70
Opened 2024-02-07 12:56 UTC by juanburgosautoglb

Change all the shotgrid/shotgun occurrences in the repository.

2024-02-20 15:46 UTC, NorberMV requested changes
I think looks good overall, just a minor typo in a code comment.

2024-02-20 15:46 UTC, NorberMV commented on info.yml
> +# linked_projects.Asset is required for references in multiple Flow Production Tracking rojects
Small typo: `Flow Production Tracking rojects` =>`Flow Production Tracking projects`

2024-02-20 15:51 UTC, NorberMV approved these changes
LGTM!

2024-02-21 11:18 UTC, rob-aitchison approved these changes

2024-03-20 18:55 UTC, merged